services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: reverse-proxy
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.api.address=:80
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - "traefik.http.routers.reverse-proxy.rule=Host(`fs-service.localhost`)"
      - "traefik.http.services.file-storage-proxy.loadbalancer.server.port=80"

  user-service:
    build:
      context: ./backend/user_service
    image: user-service
    container_name: fs-user-service
    environment:
      SQLALCHEMY_DATABASE_URI: mysql://${USER_SERVICE_DB_USER}:${USER_SERVICE_DB_PASSWORD}@${USER_SERVICE_DB_HOST}/user-db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
      ADMIN_USER_USERNAME: ${ADMIN_USER_USERNAME}
      ADMIN_USER_PASSWORD: ${ADMIN_USER_PASSWORD}
    ports:
      - "8000:80"
#    command: /start-reload.sh  # uncomment to enable auto restart
    volumes:
      - ./backend/user_service/app:/app/app
      - ./backend/user_service/alembic:/app/alembic
    depends_on:
      - user-service-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-storage-user-backend.rule=Host(`fs-service.localhost`) && (PathPrefix(`/api/users`) || PathPrefix(`/api/auth`))"
      - "traefik.http.services.file-storage-user-backend.loadbalancer.server.port=80"

  user-service-db:
    image: mysql:5.7
    container_name: ${USER_SERVICE_DB_HOST}
    volumes:
      - user_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-db
      MYSQL_USER: ${USER_SERVICE_DB_USER}
      MYSQL_PASSWORD: ${USER_SERVICE_DB_PASSWORD}

  file-service:
    build:
      context: ./backend/file_service
    image: file-service
    container_name: fs-file-service
    ports:
      - "8001:80"
#    command: /start-reload.sh  # uncomment to enable auto restart
    volumes:
      - ./backend/file_service/app:/app/app
    environment:
      MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:27017
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
    depends_on:
      - file-service-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-storage-file-backend.rule=Host(`fs-service.localhost`) && PathPrefix(`/api/files`)"
      - "traefik.http.services.file-storage-file-backend.loadbalancer.server.port=80"

  file-service-db:
    image: mongo:4.4
    container_name: ${MONGO_DB_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - file_db_data:/data/db

  frontend:
    build:
      context: ./frontend
    image: fs-frontend
    container_name: fs-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file-storage-frontend-http.rule=PathPrefix(`/`)"
      - "traefik.http.services.file-storage-frontend.loadbalancer.server.port=80"

volumes:
  user_db_data: {}
  file_db_data: {}
