name: CLI Test

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup docker-compose env
      run: docker-compose up -d
    - name: Test CLI
      working-directory: ./cli
      run: |
        pip install -r requirements.txt
        python -m pytest .
